### ISSUE TITLE
Looping through empty arrays throw error

### ISSUE THREAD

**Issue by jdmcd** [vapor/template-kit#12]
Looping through an empty array should just return an empty body instead of throwing an error.

**Comment by tanner0101** [comment]
@mcdappdev what was the error thrown?

**Comment by jdmcd** [comment]
`Could not convert iterator data to array.`

**Comment by gdahboy** [comment]
the same error here , even if change in .leaf file , but it still the same it's like there's something that stuck in memory

**Comment by foscomputerservices** [comment]
Just a thought...  

I find this error really helpful to track down problems. Without a debugger or compiler, it’s easy to miss type a variable name in either side and spend a long time tracking things down. This is especially true with embedded files. 

Doing nothing reminds me of [nil doSomething] in Objective-C, which sometimes took forever to track down.

I’m not saying that the error message shouldn’t be improved, but doing nothing on nil will make things more complicated in my experience.

**Comment by 0xTim** [comment]
Closing as template kit is not used with Vapor 4 and new behaviour is in LeafKit - if this is still an issue please create an issue on that repo. Thanks!
