### ISSUE TITLE
shared metadata

### ISSUE THREAD

**Issue by tanner0101** [vapor/template-kit#13]
Allowed for some shared metadata to be set on a renderer or serializer that can be combined with the incoming view data. This would allow for things like session data to be automatically exposed to leaf so that view data doesn't need to be repetitive.

**Comment by tonyarnold** [comment]
Could this include request metadata, such as the current URL/path being rendered? That would be super handy for rendering context sensitive items such as active navigation items.

**Comment by 0xTim** [comment]
Closing as template kit is not used with Vapor 4 and new behaviour is in LeafKit - if this is still an issue please create an issue on that repo. Thanks!
