### ISSUE TITLE
Templated/Renderable Models

### ISSUE THREAD

**Issue by ldstreet** [vapor/template-kit#21]
Note: I first posted a variation of this proposal in [Leaf](https://github.com/vapor/leaf) but have since realized that is likely more appropriate here since it does not necessarily need Leaf to function.

This is a proposal to add a standard protocol for creating reusable and composable HTML views. Currently, thanks to TemplateKit, we can populate a template using a Codable model. This is great for type safety, but can still lead to lots of redundant templates. But what if we could break the templates up into smaller pieces, tie them to corresponding models, and then compose them programmatically in Swift? I implemented a few protocols that allow just that in my current project, and I think it might benefit other Vapor developers.

Here is a breakdown of what this looks like.

First, we have our base protocols:

````
protocol Templated {
    var template: String { get }
}

protocol TemplatePathed {
    var templatePath: String { get }
}

protocol Renderable: Encodable {
    func render(using renderer: TemplateRenderer) throws -> Future<View>
}
````

Templated allows the model to define a template right in the Swift file like this:

````
struct Body: Templated {

    let text: String

    var template: String = """
    <body>#(text)</body>
    """
}
````

While TemplatePathed lets the model define the name of its corresponding template like this:

````
struct Body: Templated {

    let text: String

    var template: String = "body"
}

````

Regardless of which protocol you use, they will both help you implement Renderable.

````
extension Renderable where Self: TemplatePathed {
    public func render(using renderer: TemplateRenderer) throws -> Future<View> {
        return renderer.render(templatePath, self)
    }
}

extension Renderable where Self: Templated {

    public func render(using renderer: TemplateRenderer) throws -> Future<View> {
        guard let data = template.data(using: .utf8) else {
            throw(TemplateKitError(identifier: "badTemplateString", reason: "Template string could not be converted to data."))
        }
        return renderer.render(template: data, self)
    }
}

extension Body: Renderable {}

````

Now, you can serve up your html in Swift like this:

````
router.get { req -> Future<View> in
    let body = Body(text: "Hello, Renderable")
    return try body.render(using: try req.make(TemplateRenderer.self))
}
````

Not only that, but these Renderable models can be nested. Say I want to embed my Body inside a Div. I can do so like this:

````
struct DivWithBody: Templated, Renderable {
    let class: String
    let body: Body

    var template = """
    <div class="#(class)">
    #templatedModel(body)
    </div>
    """
}
````

Notice the #templatedModel tag. This allows us to embed a templated model inside of our HTML. It is defined as such:

````
public final class TemplatedModel: TagRenderer {
    
    public func render(tag: TagContext) throws -> EventLoopFuture<TemplateData> {
        
        try tag.requireParameterCount(1)
        
        let context = tag.parameters[0]
        
        let renderer = try tag.container.make(TemplateRenderer.self)
        
        let view: EventLoopFuture<View>
        if let templatePath = context.dictionary?["templatePath"]?.string {
            view = renderer.render(templatePath, context)
        } else if let template = context.dictionary?["template"]?.data {
            view = renderer.render(template: template, context)
        } else {
            throw(TemplateKitError(identifier: "notRenderable", reason: "First paramater must be Templated or TemplatePathed. The data supplied does not contain a templatePath or template"))
        }
        
        return view.map { view -> TemplateData in
            return .data(view.data)
        }
        
    }
}
````

But this still isn't particularly generic/reusable. Shouldn't we be able to hold any sort of renderable model inside of our Div struct? Using AnyRenderable we can make a truly reusable Div model.

````
struct Div: Templated, Renderable {
    let class: String
    let content: [AnyRenderable]

    var template = """
    <div class="#(class)">
    #for(item in content) {
        #templatedModel(item.renderable)
    }
    </div>
    """
}
````

How do we create this AnyRenderable array? With a simple map call, like this: 

````
router.get { req -> Future<View> in
    let content = [Body(title: "Hello"), Body(title: "World")].map(AnyRenderable.init)
    let div = Div(class: "my-class", content: content)
    return try div.render(using: try req.make(TemplateRenderer.self))
}
````

You can see AnyRenderable's implementation below: 

````
/// Type Erased Renderable struct
public struct AnyRenderable {
    
    /// stored renderable
    public var renderable: Renderable
    
    /// init
    public init(renderable: Renderable) {
        self.renderable = renderable
    }
    

}

/// Encodable conformance
extension AnyRenderable: Encodable {
    
    /// Coding keys for Encodable
    private enum CodingKeys: CodingKey {
        case renderable
    }
    
    /// Encode using the `Renderable` super encoder
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try renderable.encode(to: container.superEncoder(forKey: .renderable))
    }
}
````

Unfortunately, while AnyRenderable is Encodable, it is not easy to make it Decodable. This is fine for our purposes here, but I am not sure if it will creep up as a problem in the future.

I am planning on creating a PR and attaching to this issue soon, but for now, I thought I'd just see what everyone thinks. Would you use something like this? Does it belong in the TemplateKit framework? Do you have any suggestions?

Thanks!

**Comment by tanner0101** [comment]
Very interesting feature proposal. I will take a more in-depth look at this when I finalize the official Leaf release tag. From a brief reading, it seems like this might make a great third party package (potentially something in `vapor-community` if you are keen to contribute it).

You should join our team chat (discord.gg/vapor) and discuss in the #contribute section :)

**Comment by 0xTim** [comment]
Closing as template kit is not used with Vapor 4 and new behaviour is in LeafKit - if this is still an issue please create an issue on that repo. Thanks!
