### ISSUE TITLE
Impossible to access information from the Request's private container

### ISSUE THREAD

**Issue by siemensikkema** [vapor/template-kit#28]
There are several scenarios in which one might want to render using information that is tied to the lifetime of a request:
- current username
- current URL
- flash messages (see https://github.com/nodes-vapor/flash/issues/26)
- form fields and validation (see https://github.com/nodes-vapor/submissions)

For some of these cases it is possible to pass the information in as encoded data. It can quickly become inconvenient, however, in the case where the same information has to be passed into many different requests (e.g. when rendering a menu structure that depends on the current URL, or when having to display the user name in an admin panel) or when the data does not lend itself well to encoding/decoding. In those cases it is useful to use a storage service that stores the information and which can be populated using a middleware.
This storage service can then be made inside the `TagRenderer` to access the data.
In order to make sure the data does not leak out to other requests, the service should live on the request’s private container. The information in the private container is not accessible to the TagRenderer, unless the TemplateRenderer is made on the private container. The problem with doing so is that it skips any template caching and is therefore very inefficient.

**Comment by 0xTim** [comment]
Can you not use a custom renderer at this point? So instead of using `LeafRenderer` you use `LeafBuilderRenderer`. In there you take the request and build all the data you require for every request and then create a context using this and the page-specific data that was passed in. This then finally calls through to `LeafRenderer` to actually create the HTML. (Also makes testing nice and easy as well!)

**Comment by siemensikkema** [comment]
@0xTim As I believe you concluded as well in Discord after writing this, this proposed solution will not have access to the request and therefore the private container either. There would have to be an extra step to copy the request onto the custom renderer after `.make(LeafBuilderRenderer.self)` or something along those lines.

**Comment by 0xTim** [comment]
Yeah, only thing that I've come up with that avoids a private container is to wrap all `render` calls with a `renderWithData` function that adds in the extra data. That of course requires the developer to remember to use it, which isn't always easy with multiple developers

**Comment by jdmcd** [comment]
I actually don’t think that’s the worst thing in the world. Previously it was going to require every developer to create the renderer from the private container anyway so there was always going to be an extra cognitive step. What I did was I deprecated req.view() and added an extension to be req.privateView(). That way if anyone tried to use req.view() it was incredibly clear (through an Xcode warning) that it was the wrong one to use. I think if a team was super inclined they could do the same thing with the regular render method

**Comment by siemensikkema** [comment]
Alternatively, we need a breaking change in `TemplateKit` and `Leaf` as well as non-breaking changes to `Vapor`. I'm thinking of requiring the user to pass in the request to every render call (I have that working locally). This would still require casting the `container` as a `Request` in order to access the `privateContainer`. To improve this situation I would consider making `TagContext` similar to `Request` and `Response` in the sense that it would receive a `privateContainer` as well. We could create a protocol for types having both a shared and private container, to which `Request`, `Response` and `TagContext` would conform to.

**Comment by jdmcd** [comment]
That's not that far off from what I do here: https://github.com/gotranseo/template/blob/master/Sources/App/Utils/CommonViewContext/LeafRenderer%2BCommonViewContext.swift#L6

**Comment by tanner0101** [comment]
Maybe we could add some metadata (think `userInfo`) type storage to `TemplateDataContext`. Then Vapor could decide what it wants to put from the request into that metadata. A decent default could be just storing the entire request into this user info. The FlashTag could then easily fetch it out and cast. 

I think we should be looking to remove the reference to container from TagContext in the future. With the addition of https://github.com/vapor/vapor/issues/1711 in Vapor 3.1, in Vapor 4 it could make sense to no longer have `Request` be a container. With thread safe controllers, it's much easier (and gives more control) to do dependency injection during _initialization_. 

@siemensikkema we should work together planning the next release to ensure there's a good, performant solution for doing things like flashing messages (nodes-vapor/flash#26), etc.

**Comment by 0xTim** [comment]
Closing as template kit is not used with Vapor 4 and new behaviour is in LeafKit - if this is still an issue please create an issue on that repo. Thanks!
