### ISSUE TITLE
TemplateDataEncoder using base Codables

### ISSUE THREAD

**Issue by trametheka** [vapor/template-kit#30]
I'm starting to run into problems with TemplateDataEncoder. So far nothing show stopping, but something to keep in mind for the future.

At the moment the TemplateDataEncoder uses the base types implementation of Codable. For base types (string, int, double, etc) this isn't a problem as we're getting that base type back and convertToTemplateData() can be called on it.

For Date, this is a problem. Ideally for rendering a template, 1970 should be used as a reference date as this is still the "standard" for javascript and other things. While this is what TemplateDataRepresentable is doing (subject to #20), it is never called as the base implementation of Codable in Foundation returns a Double instead of the Date object which is using 2001 as a reference date.

This isn't a big deal for now, I just have a tag to convert it back into a Date and then spit out timeIntervalSince1970, but this will cause issues and already adds overhead if more types want to be conformed to TemplateDataRepresentable. The only solution I can really see is to copy JsonEncoders boxing technique as encode/decode on types can't be simply overriden.

**Comment by tanner0101** [comment]
This has been fixed in #31. See #20. Thanks for reporting!
