### ISSUE TITLE
PlaintextRenderer does not conform to ViewRenderer

### ISSUE THREAD

**Issue by vzsg** [vapor/template-kit#35]
...even though Vapor's [default service configuration](https://github.com/vapor/vapor/blob/master/Sources/Vapor/Services/Services%2BDefault.swift#L77-L80) registers it as such, leading to crashes with a failed force cast.

---

(Why registering an unrelated type for a service is not a compile time error would probably be a separate issue for vapor/service.)

**Comment by tanner0101** [comment]
Hmm.. On master it appears to conform to TemplateRenderer (https://github.com/vapor/template-kit/blob/master/Sources/TemplateKit/Pipeline/PlaintextRenderer.swift#L2) which in turn conforms to ViewRenderer (https://github.com/vapor/template-kit/blob/master/Sources/TemplateKit/Pipeline/TemplateRenderer.swift#L12). Am I missing something?

**Comment by vzsg** [comment]
No, you aren't. The commit that closed #17 also fixed the crash, I just forgot to update my toybox project before writing this 🤦‍♂️ ... Sorry.
