### ISSUE TITLE
No file was found at path on Ubuntu

### ISSUE THREAD

**Issue by makoni** [vapor/template-kit#39]
My template is in path:

/home/webserver/site/Resources/Views/main.leaf

I use code to render temlate:
return try req.view().render("main")

On Ubuntu there's error:
 [ ERROR ] TemplateKitError.fileNotFound: No file was found at path: /home/webserver/Resources/Views/main.leaf (TemplateRenderer.swift:78)

TemplateKit tries to find the template at wrong path on Ubuntu. But it works fine on macOS.

**Comment by vzsg** [comment]
This is not a Vapor or Vapor+Linux issue, but some misconfiguration in your local environment.

You should have `/home/webserver/site` as your current working directory when you launch the application. It seems you have `/home/webserver` instead.

**Comment by cleverer** [comment]
I think this might be related to https://github.com/vapor/core/pull/173
