### ISSUE TITLE
Data is nil for bool TemplateData

### ISSUE THREAD

**Issue by Igor-Palaguta** [vapor/template-kit#57]
Is is expected that `data: Data?` in `TemplateData` does not handle bool case and returns nil from `default`

So no ability to return from custom tag `.bool` as it throws error `Unable to convert tag return type to Data`

https://github.com/vapor/template-kit/blob/master/Sources/TemplateKit/Data/TemplateData.swift#L173

**Comment by 0xTim** [comment]
Closing as template kit is not used with Vapor 4 and new behaviour is in LeafKit - if this is still an issue please create an issue on that repo. Thanks!
