### ISSUE TITLE
Template throws if it starts with comment syntax #//

### ISSUE THREAD

**Issue by cHaLkdusT** [vapor/template-kit#59]
Apparently, if a template starts with `#//` syntax, it throws a _Fatal error: Index out of range_. However, it works fine if first line is empty
```

#// Comment
<!DOCTYPE html>
<html lang="en">
<head>
<title>TemplateKit</title>
</head>
<body>
</body>
</html>
```

**Comment by 0xTim** [comment]
Closing as template kit is not used with Vapor 4 and new behaviour is in LeafKit - if this is still an issue please create an issue on that repo. Thanks!
